### ISSUE TITLE
Create, maintain design docs

### ISSUE THREAD

**Issue by willebra** [doubleopen-project/dos#11]
- [ ] Create and maintain design docs for
- [ ] Determine place(s) to create, maintain, and publish design docs. 
- [x] Design High level architecture
- [x] Design data models & database schema
- [x] Design sequence diagrams
- [ ] Design state diagrams 
- [ ] Design front-end use case (curator) description, UI mockups

Draft high-level architecture pic: https://excalidraw.com/#room=e937110aba626d41cd0f,i_GK4G0z-7PoDIWW2LKZUQ

**Comment by willebra** [comment]
Front-end use case description draft: https://docs.google.com/presentation/d/1Y6DAXIiFrZZkNok_dn9o5iLE1j3E313g/edit#slide=id.p1

**Comment by Etsija** [comment]
Scanner Agent design document:

https://docs.google.com/presentation/d/1-WmHwTsfgzy3zDaGzUFKvD3dWTe_Nn2-?rtpof=true&authuser=jyrki.keisala%40doubleopen.org&usp=drive_fs

**Comment by Etsija** [comment]
DOS / scanning new code: sequence diagram added

https://drive.google.com/open?id=1NS6sG2DfCiZglAfc3zAzwWsX_kGnBNei&authuser=jyrki.keisala%40doubleopen.org&usp=drive_fs

**Comment by Etsija** [comment]
Test comment.
