### ISSUE TITLE
Add curation of the license findings

### ISSUE THREAD

**Issue by mmurto** [doubleopen-project/dos#3]
Users should be able to curate the license findings made by the scanner and save the curations to the database.

- [x] #8
- [ ] Allow viewing license findings through the UI
- [ ] Allow curating license findings through the UI
- [ ] Provide curated license information to users through the API
